/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CTabbar: typeof import('./src/components/ct-tabbar/CTabbar.vue')['default']
    ListItemT3: typeof import('./src/components/list-item-type/ListItemT3.vue')['default']
    ListItemT9: typeof import('./src/components/list-item-type/ListItemT9.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/tabbar/TabBar.vue')['default']
    TabBar2: typeof import('./src/components/TabBar2.vue')['default']
    TLoading: typeof import('./src/components/loading/TLoading.vue')['default']
    VanButton: typeof import("vant/es")["Button"]
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import("vant/es")["Cell"]
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import("vant/es")["Image"]
    VanIndexAnchor: typeof import("vant/es")["IndexAnchor"]
    VanIndexBar: typeof import("vant/es")["IndexBar"]
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import("vant/es")["Search"]
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import("vant/es")["Tab"]
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import("vant/es")["Tabs"]
  }
}
